projects:
  test-project:
    name: test-project
    path: /Users/wyatt.johnson/Code/github.com/wyattjoh/claude-sync/test-temp
    branch: main
    autoTrack: true
    trackedFiles:
      - CLAUDE.local.md
    metadata:
      addedAt: '2025-08-03T02:21:53.042Z'
      lastSync: '2025-08-03T02:21:53.042Z'
      lastModified: '2025-08-03T02:21:53.042Z'
